@props(['genres', 'artists', 'labels', 'filters'])
<aside class="filter-sidebar"><div class="filter-heading"><h2>Filter & sort</h2><a href="{{ url()->current() }}">Clear</a></div><form method="GET" action="{{ url()->current() }}">
    <x-search-bar :value="$filters['q'] ?? ''" />
    <label>Genre<select name="genre"><option value="">All genres</option>@foreach($genres as $genre)<option value="{{ $genre->slug }}" @selected(($filters['genre'] ?? '') === $genre->slug)>{{ $genre->name }}</option>@endforeach</select></label>
    <label>Artist<select name="artist"><option value="">All artists</option>@foreach($artists as $artist)<option value="{{ $artist->slug }}" @selected(($filters['artist'] ?? '') === $artist->slug)>{{ $artist->name }}</option>@endforeach</select></label>
    <label>Label<select name="label"><option value="">All labels</option>@foreach($labels as $label)<option value="{{ $label->slug }}" @selected(($filters['label'] ?? '') === $label->slug)>{{ $label->name }}</option>@endforeach</select></label>
    <div class="filter-price"><label>Min price<input type="number" name="min_price" min="0" step="0.01" value="{{ $filters['min_price'] ?? '' }}" placeholder="$0"></label><label>Max price<input type="number" name="max_price" min="0" step="0.01" value="{{ $filters['max_price'] ?? '' }}" placeholder="Any"></label></div>
    <label>Availability<select name="availability"><option value="">Any</option><option value="in-stock" @selected(($filters['availability'] ?? '') === 'in-stock')>In stock</option><option value="preorder" @selected(($filters['availability'] ?? '') === 'preorder')>Pre-order</option></select></label>
    <label>Sort by<select name="sort"><option value="newest" @selected(($filters['sort'] ?? '') === 'newest')>Newest</option><option value="price-low" @selected(($filters['sort'] ?? '') === 'price-low')>Price: low to high</option><option value="price-high" @selected(($filters['sort'] ?? '') === 'price-high')>Price: high to low</option><option value="name" @selected(($filters['sort'] ?? '') === 'name')>Title A–Z</option></select></label>
    <button class="button button-dark" type="submit">Apply filters <span aria-hidden="true">↗</span></button>
</form></aside>
